name: 'Condition-based Pull Request labeler'
description: 'Label Pull Requests based on rules'
author: 'Galo Navarro <anglorvaroa@gmail.com>'
inputs: 
  config_path:
    description: 'Path for labeling rules'
    default: '.github/labeler.yml'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: award
  color: blue
