name: Label PRs

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: srvaroa/labeler@master
    - name: Label PRs
      run: |
        go build -o action ./cmd
        ./action
